export default {
    COLORS: {
      BACKGROUND_APP: "#1C1B1E",
      BACKGROUND_INPUTS: "#262529",
      BACKGROUND_MOVIENOTES: "#272024",
      BACKGROUND_MOVIETAGS: "#312E38",
      BACKGROUND_MARKDOWN: "#0D0C0F",
      BACKGROUND_DARK: "#0D0C0F",
  
      PINK: "#FF859B",
      INPUTS_SPANS: "#948F99",
      MAIN_TEXT: "#F4EDE8",
      WHITE: "#FFFFFF"
    }
  }